---
title: "p8105_hw5_pl2848"
author: "Pei Liu"
date: "2022-11-10"
output: github_document
---



```{r, include = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1
```{r}
file_names <- list.files(path = "data")

file_names <- paste0('data/', file_names)

```


```{r}
map(file_names, read_csv)
```


```{r}
# read the file and add new column city_state
homicide = read_csv("data-homicides-master/homicide-data.csv") %>% 
  mutate(city_state = paste(city, state, sep =", "))
```




```{r}
# a function to determine whether the case was solved or not
solved_or_not = function(x){
  if(x == "Closed by arrest") {"solved"}
  else "unsolved"
}

# Added a new column to see if the case was solved or unsolved
homicide_by_city = homicide %>% 
  mutate(status = as.character(map(disposition, solved_or_not))) %>% 
  group_by(status, city_state) %>% 
  summarise(number_of_homicides = n()) %>% 
  pivot_wider(names_from = status,
              values_from = number_of_homicides) 
  


homicide_by_city_total = homicide %>% 
  mutate(status = as.character(map(disposition, solved_or_not))) %>% 
  group_by(city_state) %>% 
  summarise(number_of_homicides = n()) 
  
homicide_df = full_join(homicide_by_city,homicide_by_city_total)  

homicide_df[is.na(homicide_df)] <- 0  
homicide_df
```

save the output of prop.test as an R object, apply the broom::tidy to this object and pull the estimated proportion and confidence intervals from the resulting tidy dataframe.
```{r}
BMD_unsolved_test = prop.test(1825, 2827, p = NULL,alternative = "two.sided",conf.level = 0.95, correct = TRUE) 
  


BMD_unsolved_test = broom::tidy(BMD_unsolved_test) %>% 
  select(estimate, conf.low, conf.high)

BMD_unsolved_test
```


Now run prop.test for each of the cities in your dataset, and extract both the proportion of unsolved homicides and the confidence interval for each.
```{r}

city_prop_test = function(x,y){
  test_data = prop.test(x, y, p = NULL,conf.level = 0.95, correct = TRUE) %>%
    broom::tidy()
}

homicide_prop_test = 
tibble(
  city_state = homicide_df$city_state,
  test_result = purrr::map2(homicide_df$unsolved,homicide_df$number_of_homicides, city_prop_test)) %>% 
  unnest(cols = c(test_result)) %>% 
  select(c(city_state, estimate, conf.low, conf.high))

homicide_prop_test

```


```{r}
homicide_prop_test %>% 
  name = forcats::fct_reorder(name, tmax) %>% 
  ggplot(aes(x = city_state, y = estimate))+ 
  geom_point(alpha = .5) +
  geom_boxplot() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  )
```

